spring:
  datasource:
    dbcp2:
      initial-size: 2
      max-wait-millis: 60000
      min-idle: 20
      test-on-borrow: true
      test-on-return: false
      test-while-idle: true
      validation-query: SELECT 1
    driver-class-name: com.mysql.cj.jdbc.Driver
    password: IKNe8LljHCHPl4Dx
    url: jdbc:mysql://db.tcreopargh.xyz:3306/amttd?allowPublicKeyRetrieval=true&useSSL=true
    username: root
  jpa:
    show-sql: true
    database-platform: org.hibernate.dialect.MySQL5Dialect
    generate-ddl: true
    hibernate:
      ddl-auto: update
  mvc:
    converters:
      preferred-json-mapper: gson
logging:
  level:
    root: INFO

